parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\ExchangeRateProvider\BinanceExchangeRateProvider:
        arguments:
            - '@http_client'

    App\Service\ExchangeRateService:
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@App\Repository\BinanceExchangeRateRepository'
            - '@App\Service\ExchangeRateProvider\BinanceExchangeRateProvider'

    App\Command\UpdateBinanceRatesCommand:
        arguments:
            - '@App\Service\ExchangeRateService'
            - '@Psr\Log\LoggerInterface'

    App\Controller\Api\BinanceRateController:
        arguments:
            - '@App\Service\ExchangeRateService'
            - '@App\Validator\BinanceDateRangeValidator'